// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, uri_does_not_exist, undefined_method, const_initialized_with_non_constant_value
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjxwTHUNEXTsT1ekhh8tefs8nSLVECh0',
    appId: '1:139937246139:web:2c649a94da11f68caf329e',
    messagingSenderId: '139937246139',
    projectId: 'pasahero-57f9f',
    authDomain: 'pasahero-57f9f.firebaseapp.com',
    storageBucket: 'pasahero-57f9f.firebasestorage.app',
    measurementId: 'G-4M9EQPVBQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUsOx_HATizbf70hvWK-g5hsTbGJMzSY',
    appId: '1:139937246139:android:2da920f6d953d7d5af329e',
    messagingSenderId: '139937246139',
    projectId: 'pasahero-57f9f',
    storageBucket: 'pasahero-57f9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZPh-cmYEqtG--BQVdFr0VivBqf8OZXk',
    appId: '1:139937246139:ios:a643a47e1b4b4b20af329e',
    messagingSenderId: '139937246139',
    projectId: 'pasahero-57f9f',
    storageBucket: 'pasahero-57f9f.firebasestorage.app',
    iosBundleId: 'com.pasahero.pasahero',
  );
}
